name: default_rnn
data:
  data_dir: '../data/download/files/'
  csv_out: 'data.csv'
  batch_size: 2
  shuffle: True
  img_height: 128
  dataset_split: [80, 10, 10]  # train, val, test
  vocab_pitch_path: './vocab/rnn_pitch.txt'
  vocab_length_path: './vocab/rnn_rhythm.txt'
  max_chord_stack: 10
model:
  img_channels: 1
  conv_blocks: 4
  conv_filter_n: [32, 64, 128, 256]
  conv_filter_size: [ [3,3], [3,3], [3,3], [3,3] ]
  conv_pooling_size: [ [2,2], [2,2], [2,2], [2,2] ]
  rnn_units: 512
  rnn_layers: 2
  dropout: TODO
training:
  random_seed: 42
  lr: 1e-4
  max_epochs: 500
